### PR TITLE
Use ignore package in  copy workflow

### LINKED ISSUE #12: .gitignore like .distignore functionality
.distignore doesn't work the same way you would expect .gitignore to work, as in it doesn't work when we use gitignore-regex in the filepath.

This can be solved by using `ignore` package: https://www.npmjs.com/package/ignore

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Using ignore package, now copy task will make distignore work similar to how gitignore works. Closes https://github.com/Codeinwp/grunt-plugin-fleet/issues/12

@selul Can you or someone test this to make sure it works everywhere? We also need test tested on a Windows.

### CODE REVIEW

**Comment by selul** [comment]
@HardeepAsrani for you it worked on otter?

**Comment by HardeepAsrani** [comment]
@selul It worked for me. I used `*`, `**` and `!` in dir patterns and everything worked just fine.

**Comment by HardeepAsrani** [comment]
For me the next step is to remove the folder which don't have any files after filtering files out.

**Comment by HardeepAsrani** [comment]
@selul Did you test it before merging? Don't want it to cause issues with other plugins. 😄

**Pull request merged**
